name: "Update Snyk Job listings based on Greenhouse"
on:
  push:
    branches:
      - master
    paths:
      - "*"
      - "!README.md"
  schedule:
    # Run workflow once an hour to grab the very latest Snyk roles available
    - cron: "0 * * * *"

jobs:
  brew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Render latest template
        run: |
          ruby render.rb
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COMMIT_MSG: |
            Updated jobs from Greenhouse
            skip-checks: true
        run: |
          # Hard-code user config
          git config user.email "snyksec@users.noreply.github.com"
          git config user.name "Snyk"
          git config --get-regexp "user\.(name|email)"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Checkout the branch so we can push back to it
          git checkout master
          git add .
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
